#!/usr/bin/env python3
"""Export the trained model + front-end tables as C headers.

  kws_tables.h      -> board/contest_board/src/   (front-end constants)
  kws_model_data.h  -> board/contest_board/src/   (folded conv weights)
  kws_golden.h      -> tools/kws/host/            (parity test vectors)

--random: skip the checkpoint, use a seeded untrained model and a synthetic
chirp+noise golden signal.  That validates the C front end and NN loops
against torch before any training data exists.  Re-run without --random
after train.py to emit the real weights and the real golden windows.
"""

import json
import sys
from pathlib import Path

import numpy as np
import torch

import kws_common as K
from train import DSCNN, ARCH

ROOT = Path(__file__).parent
SRC = ROOT.parent.parent / "board" / "contest_board" / "src"
HOST = ROOT / "host"
DATA = ROOT / "data"
CKPT = ROOT / "checkpoints"


def fmt(arr, per_line=8):
    a = np.asarray(arr).ravel()
    lines = []
    for i in range(0, len(a), per_line):
        lines.append("  " + ", ".join(f"{v:.8e}f" for v in a[i:i + per_line])
                     + ",")
    return "\n".join(lines)


def fmt_i16(arr, per_line=12):
    a = np.asarray(arr).ravel()
    lines = []
    for i in range(0, len(a), per_line):
        lines.append("  " + ", ".join(str(int(v)) for v in a[i:i + per_line])
                     + ",")
    return "\n".join(lines)


def fold_bn(w, bn):
    g = bn.weight.detach().numpy()
    b = bn.bias.detach().numpy()
    mu = bn.running_mean.detach().numpy()
    var = bn.running_var.detach().numpy()
    scale = g / np.sqrt(var + bn.eps)
    wf = w.detach().numpy() * scale.reshape(-1, 1, 1, 1)
    bf = b - mu * scale
    return wf.astype(np.float32), bf.astype(np.float32)


def emit_tables(mean, istd, threshold):
    hann = K.hann_window()
    fb = K.mel_filterbank()
    start, length, weights = [], [], []
    for m in range(K.NMEL):
        nz = np.flatnonzero(fb[m] > 0)
        s, e = (int(nz[0]), int(nz[-1] + 1)) if len(nz) else (0, 0)
        start.append(s)
        length.append(e - s)
        weights.append(fb[m, s:e])
    off = np.concatenate([[0], np.cumsum(length)[:-1]])
    wcat = np.concatenate(weights) if weights else np.zeros(0)
    k = np.arange(K.NFFT // 2)
    tw_c = np.cos(2 * np.pi * k / K.NFFT).astype(np.float32)
    tw_s = np.sin(2 * np.pi * k / K.NFFT).astype(np.float32)

    h = f"""/* AUTO-GENERATED by tools/kws/export_c.py — DO NOT EDIT.
 * Front-end tables; numerics defined by tools/kws/kws_common.py.
 */

#ifndef __KWS_TABLES_H
#define __KWS_TABLES_H

#define KWS_SR        {K.SR}
#define KWS_WIN       {K.WIN}
#define KWS_HOP       {K.HOP}
#define KWS_NFFT      {K.NFFT}
#define KWS_NBIN      {K.NBIN}
#define KWS_NMEL      {K.NMEL}
#define KWS_T         {K.T_FRAMES}
#define KWS_LOG_EPS   1e-6f
#define KWS_MEL_TOTAL {len(wcat)}
#define KWS_DEFAULT_THRESHOLD {threshold:.3f}f

static const float g_kws_hann[KWS_WIN] =
{{
{fmt(hann)}
}};

/* twiddle k -> (cos, sin) of 2*pi*k/NFFT; FFT applies e^(-j*theta) */

static const float g_kws_tw_cos[KWS_NFFT / 2] =
{{
{fmt(tw_c)}
}};

static const float g_kws_tw_sin[KWS_NFFT / 2] =
{{
{fmt(tw_s)}
}};

static const int16_t g_kws_mel_start[KWS_NMEL] =
{{
{fmt_i16(start)}
}};

static const int16_t g_kws_mel_len[KWS_NMEL] =
{{
{fmt_i16(length)}
}};

static const int16_t g_kws_mel_off[KWS_NMEL] =
{{
{fmt_i16(off)}
}};

static const float g_kws_mel_w[KWS_MEL_TOTAL] =
{{
{fmt(wcat)}
}};

static const float g_kws_norm_mean[KWS_NMEL] =
{{
{fmt(mean)}
}};

static const float g_kws_norm_istd[KWS_NMEL] =
{{
{fmt(istd)}
}};

#endif /* __KWS_TABLES_H */
"""
    (SRC / "kws_tables.h").write_text(h)


def emit_model(model):
    c = ARCH["ch"]
    c1w, c1b = fold_bn(model.conv1.weight, model.bn1)
    dws, pws = [], []
    for i in range(ARCH["blocks"]):
        dws.append(fold_bn(model.dw[i].weight, model.dwbn[i]))
        pws.append(fold_bn(model.pw[i].weight, model.pwbn[i]))
    fcw = model.fc.weight.detach().numpy().astype(np.float32)
    fcb = model.fc.bias.detach().numpy().astype(np.float32)

    t_out = (ARCH["t"] + 2 * ARCH["conv1_p"][0] - ARCH["conv1_k"][0]) \
        // ARCH["conv1_s"][0] + 1
    m_out = (ARCH["m"] + 2 * ARCH["conv1_p"][1] - ARCH["conv1_k"][1]) \
        // ARCH["conv1_s"][1] + 1

    parts = [f"""/* AUTO-GENERATED by tools/kws/export_c.py — DO NOT EDIT.
 * DS-CNN weights, BatchNorm folded.  Arch defined in tools/kws/train.py.
 */

#ifndef __KWS_MODEL_DATA_H
#define __KWS_MODEL_DATA_H

#define KWS_CH       {c}
#define KWS_BLOCKS   {ARCH["blocks"]}
#define KWS_IN_T     {ARCH["t"]}
#define KWS_IN_M     {ARCH["m"]}
#define KWS_C1_KT    {ARCH["conv1_k"][0]}
#define KWS_C1_KM    {ARCH["conv1_k"][1]}
#define KWS_C1_ST    {ARCH["conv1_s"][0]}
#define KWS_C1_SM    {ARCH["conv1_s"][1]}
#define KWS_C1_PT    {ARCH["conv1_p"][0]}
#define KWS_C1_PM    {ARCH["conv1_p"][1]}
#define KWS_C1_H     {t_out}
#define KWS_C1_W     {m_out}
#define KWS_PIX      (KWS_C1_H * KWS_C1_W)

static const float g_kws_conv1_w[KWS_CH * KWS_C1_KT * KWS_C1_KM] =
{{
{fmt(c1w)}
}};

static const float g_kws_conv1_b[KWS_CH] =
{{
{fmt(c1b)}
}};
"""]
    for i, ((dw, db), (pw, pb)) in enumerate(zip(dws, pws)):
        parts.append(f"""
static const float g_kws_dw{i}_w[KWS_CH * 9] =
{{
{fmt(dw)}
}};

static const float g_kws_dw{i}_b[KWS_CH] =
{{
{fmt(db)}
}};

static const float g_kws_pw{i}_w[KWS_CH * KWS_CH] =
{{
{fmt(pw)}
}};

static const float g_kws_pw{i}_b[KWS_CH] =
{{
{fmt(pb)}
}};
""")
    dwn = ", ".join(f"g_kws_dw{i}_w" for i in range(ARCH["blocks"]))
    dbn = ", ".join(f"g_kws_dw{i}_b" for i in range(ARCH["blocks"]))
    pwn = ", ".join(f"g_kws_pw{i}_w" for i in range(ARCH["blocks"]))
    pbn = ", ".join(f"g_kws_pw{i}_b" for i in range(ARCH["blocks"]))
    parts.append(f"""
static const float *const g_kws_dw_w[KWS_BLOCKS] = {{ {dwn} }};
static const float *const g_kws_dw_b[KWS_BLOCKS] = {{ {dbn} }};
static const float *const g_kws_pw_w[KWS_BLOCKS] = {{ {pwn} }};
static const float *const g_kws_pw_b[KWS_BLOCKS] = {{ {pbn} }};

static const float g_kws_fc_w[2 * KWS_CH] =
{{
{fmt(fcw)}
}};

static const float g_kws_fc_b[2] =
{{
{fmt(fcb)}
}};

#endif /* __KWS_MODEL_DATA_H */
""")
    (SRC / "kws_model_data.h").write_text("".join(parts))


@torch.no_grad()
def model_prob(model, feat_norm):
    # per-window CMN, matching kws_nn.c and train.py
    f = feat_norm.astype(np.float32)
    f = f - f.mean(axis=0, keepdims=True)
    x = torch.from_numpy(f)[None, None]
    return float(torch.softmax(model(x), dim=1)[0, 1])


def emit_golden(model, mean, std, cases):
    HOST.mkdir(exist_ok=True)
    parts = ["""/* AUTO-GENERATED by tools/kws/export_c.py — DO NOT EDIT.
 * Parity vectors: int16 window -> expected normalized log-mel + P(wake).
 */

#ifndef __KWS_GOLDEN_H
#define __KWS_GOLDEN_H
"""]
    names = []
    for name, pcm in cases.items():
        feat = (K.logmel(pcm) - mean) / std
        prob = model_prob(model, feat)
        parts.append(f"""
static const int16_t g_gold_{name}_pcm[{len(pcm)}] =
{{
{fmt_i16(pcm)}
}};

static const float g_gold_{name}_feat[{feat.shape[0]} * {feat.shape[1]}] =
{{
{fmt(feat)}
}};

static const float g_gold_{name}_prob = {prob:.8e}f;
""")
        names.append((name, len(pcm), feat.shape[0]))
        print(f"golden '{name}': {len(pcm)} samples, prob={prob:.6f}")
    entries = ",\n".join(
        f'  {{ "{n}", g_gold_{n}_pcm, {ns}, g_gold_{n}_feat, {nf}, '
        f"&g_gold_{n}_prob }}" for n, ns, nf in names)
    parts.append(f"""
struct kws_golden_case
{{
  const char *name;
  const int16_t *pcm;
  int nsamples;
  const float *feat;
  int nframes;
  const float *prob;
}};

static const struct kws_golden_case g_kws_golden[] =
{{
{entries}
}};

#define KWS_GOLDEN_COUNT {len(names)}

#endif /* __KWS_GOLDEN_H */
""")
    (HOST / "kws_golden.h").write_text("".join(parts))


def synth_signal():
    """Deterministic chirp+tones+noise, 1.5 s — exercises all mel bins."""
    rng = np.random.default_rng(1234)
    n = K.WINDOW_SAMPLES
    t = np.arange(n) / K.SR
    f = 100 + (6000 - 100) * t / t[-1]
    x = 0.4 * np.sin(2 * np.pi * np.cumsum(f) / K.SR)
    x += 0.2 * np.sin(2 * np.pi * 440 * t) + 0.05 * rng.standard_normal(n)
    x[: n // 8] = 0.0                     # a quiet region too
    return (np.clip(x, -1, 1) * 20000).astype(np.int16)


def main():
    random_mode = "--random" in sys.argv
    torch.manual_seed(7)
    if random_mode:
        model = DSCNN().eval()
        mean = np.zeros(K.NMEL, dtype=np.float32)
        std = np.ones(K.NMEL, dtype=np.float32)
        threshold = 0.85
        cases = {"synth": synth_signal()}
        print("RANDOM export (untrained weights, synthetic golden)")
    else:
        ck = torch.load(CKPT / "model_best.pt", map_location="cpu",
                        weights_only=False)
        model = DSCNN().eval()
        model.load_state_dict(ck["state_dict"])
        mean, std = ck["mean"], ck["std"]
        threshold = json.loads((CKPT / "config.json").read_text())["threshold"]
        g = np.load(DATA / "golden.npz")
        cases = {"pos": g["pos_pcm"].astype(np.int16),
                 "neg": g["neg_pcm"].astype(np.int16),
                 "synth": synth_signal()}
    emit_tables(mean, 1.0 / std, threshold)
    emit_model(model)
    emit_golden(model, mean, std, cases)
    print(f"wrote {SRC / 'kws_tables.h'}")
    print(f"wrote {SRC / 'kws_model_data.h'}")
    print(f"wrote {HOST / 'kws_golden.h'}")


if __name__ == "__main__":
    main()
